---
title: Gebruik primaire, secundaire en tertiaire kleurklassen
hero_image: images/banner.png
description: Gebruik primaire, secundaire en tertiaire klassen om kleuren voor elementen in te stellen.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Gebruik primaire, secundaire en tertiaire kleurklassen
