title: Gebruik primaire, secundaire en tertiaire kleur classes
hero_image: images/banner.png
description: Gebruik primaire, secundaire en tertiaire classes om kleuren voor elementen in te stellen.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Gebruik primaire, secundaire en tertiaire kleur classes
