title: Use primary, secondary, and tertiary colour classes
hero_image: images/banner.png
description: Use primary, secondary, and tertiary classes to set colours for elements. 
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Use primary, secondary, and tertiary colour classes
