title: Utiliser les classes de couleur primaire, secondaire et tertiaire
hero_image: images/banner.png
description: Utilise les classes primaires, secondaires et tertiaires pour définir les couleurs des éléments.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Utiliser les classes de couleur primaire, secondaire et tertiaire
